site_name: Palmetto Documentation

nav:
  - Home: index.md
  - About: about.md
  - News: news.md
  - Owner: owner.md
  - Basic:
    - New Account Request: basic/new.md
    - Login: basic/login.md
    - Getting Started: basic/started.md
    - JupyterLab: basic/jupyter.md
    - X11 tunneling: basic/x11_tunneling.md
    - VNC: basic/vnc.md
  - Advanced:
    - Socket Proxy Access: advanced/proxy.md
    - DGX user guide: advanced/dgx.md
  - Open OnDemand:
    - Introduction: openondemand/intro.md
    - Files: openondemand/files.md
    - Jobs: openondemand/jobs.md
    - Clusters: openondemand/clusters.md
    - Interactive Apps: openondemand/apps.md
  - Software:
    - Software on Palmetto: software/software.md
    - User Software Installation: software/spack.md
    - Software Development: software/programming.md
  - Training and Outreach:
    - Training Schedule: training/schedule.md
    - Workshop Descriptions: training/workshop.md
  - Misc:
    - FAQ/Common Issues: faq/common.md
    - Facilities Document: faq/fac.md

theme: readthedocs

markdown_extensions:
  - markdown_include.include:
      base_path: docs

extra_css:
  - css/extra.css

plugins:
  - search
