site_name: Palmetto Documentation

nav:
  - Home: index.md
  - About: about.md
  - News: news.md
  - Owner: owner.md
  - Basic:
    - Login: basic/login.md
    - JupyterLab: basic/jupyter.md
  - Software: 
    - Software on Palmetto: software/software.md
    - User Software Installation: software/spack.md
    - Software Development: software/programming.md
  - Training and Outreach:
    - Training Schedule: training/schedule.md 
    - Workshop Descriptions: training/workshop.md
  - Misc: 
    - Common Issues: faq/common.md
    - FAQ: faq/faq.md

theme: readthedocs

markdown_extensions:
  - markdown_include.include:
      base_path: docs

plugins:
  - search