site_name: Palmetto Documentation

nav:
  - Home: index.md
  - About: about.md
  - News: news.md
  - Owner: owner.md
  - Basic:
    - New Account Request: basic/new.md
    - Login: basic/login.md
    - Getting Started: basic/started.md
    - JupyterLab: basic/jupyter.md
  - Software: 
    - Software on Palmetto: software/software.md
    - User Software Installation: software/spack.md
    - Software Development: software/programming.md
  - Training and Outreach:
    - Training Schedule: training/schedule.md 
    - Workshop Descriptions: training/workshop.md
  - Misc: 
    - FAQ/Common Issues: faq/common.md
    - Facilities Document: faq/fac.md

theme: readthedocs

markdown_extensions:
  - markdown_include.include:
      base_path: docs

extra_css:
  - css/extra.css

plugins:
  - search